apiVersion: v1
kind: ReplicationController
metadata:
  name: rccaddy
spec:
  replicas: 3
  selector:
    app: caddyweb
  template:
    metadata:
      name: caddy
      labels:
        app: caddyweb
    spec:
      containers:
      - name: caddyweb
        image: yobasystems/alpine-caddy
        ports:
        - containerPort: 2015